### ISSUE TITLE
wifi and Bluetooth, sound not working need help with gpu

### ISSUE THREAD

**Issue by superdistro** [Senshi111/fedora-hyprland-hyprdots#1]
Hi as said the wifi and Bluetooth is not working after installation there were some problems with my my graphics and can't  even access hyprland is there any way to disable the new greeter I don't want to set my primary gpu to nvidia and want to let it be to my intel Integrated any help will be appreciated thank you

**Comment by Senshi111** [comment]
> Hi as said the wifi and Bluetooth is not working after installation there were some problems with my my graphics and can't even access hyprland is there any way to disable the new greeter I don't want to set my primary gpu to nvidia and want to let it be to my intel Integrated any help will be appreciated thank you

sure just comment out in instal_hyprland.sh 
`if nvidia_detected; then
    # Install hyprland-nvidia-git and nvidia automatically if an NVIDIA GPU is detected
    sudo dnf install -y akmod-nvidia xorg-x11-drv-nvidia-cuda
   
fi`
